name: WesleyDev
version: 1.13.0
api-version: 1.13
main: nl.wesleydev.wesleydev.WesleyDevPlugin
depend:
  - Vault
commands:
  wesleydev:
    description: Main command of WesleyDev
    aliases: [wd]
    usage: /<command> [buy <item [amount]>]